networks:
  biggr-net:
    name: biggr-net
    external: false

services:
  cobradb-test:
    build: .
    depends_on:
      biggr-db:
        condition: service_healthy
    networks:
      - biggr-net
    volumes:
      - /data/biggr-genbank:/genbank
    stdin_open: true
    tty: true
  biggr-db:
    container_name: cobradb-postgres
    image: postgres
    restart: always
    volumes:
      - /data/biggr-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - .env
    networks:
      - biggr-net
